/// <reference types="bun-types" />

import { afterAll, beforeAll, describe, expect, setDefaultTimeout, test } from "bun:test"
import { NextRequest } from "next/server"
import { db } from "@/lib/db"
import { createSession, SESSION_COOKIE_NAME } from "@/lib/auth"
import { getReviewModerationExpiry } from "@/lib/review-moderation-policy"
import { mutateReviewModerationRequest } from "@/lib/review-moderation-superadmin"
import { addBusinessReviewModerationInformation, getBusinessReviewModerationHistory, isReviewModerationBusinessConflict } from "@/lib/review-moderation-business"
import { POST as postInformation } from "@/app/api/negocio/solicitudes-revision-resenas/[id]/informacion-adicional/route"
import { GET as getHistory } from "@/app/api/negocio/resenas/[id]/solicitudes-revision/route"

const prefix = "test-t19d-"
setDefaultTimeout(30_000)
let negocioA = "", negocioB = "", cliente = "", admin = "", tokenA = ""

async function createReview(negocioId: string, score: number, suffix: string, anonymized = false) {
  const negocio = await db.negocio.findUniqueOrThrow({ where: { id: negocioId }, select: { slug: true, nombre: true } })
  const client = await db.cliente.findUniqueOrThrow({ where: { id: cliente }, select: { nombre: true } })
  const pedido = await db.pedido.create({ data: { negocioId, negocioSlug: negocio.slug, negocioNombre: negocio.nombre, clienteId: cliente, clienteNombre: client.nombre, total: 10, totalProductos: 10, estado: "entregado", metodoEntrega: "retiro", metodoPago: "efectivo", notas: `${prefix}${suffix}` } })
  const resena = await db.resena.create({ data: { negocioId, clienteId: cliente, clienteNombre: anonymized ? "Usuario eliminado" : client.nombre, pedidoId: pedido.id, puntuacion: score, comentario: `${prefix}${suffix}`, estadoModeracion: "OCULTA_EN_REVISION", moderadaEn: new Date() } })
  if (anonymized) return db.resena.update({ where: { id: resena.id }, data: { clienteId: null } })
  return resena
}
async function createRequest(resenaId: string, negocioId = negocioA, extension = false) {
  return db.solicitudRevisionResena.create({ data: { resenaId, negocioId, motivo: "FALSA", explicacionOriginal: `${prefix}request`, estado: "REQUIERE_INFORMACION", activeKey: resenaId, venceEn: new Date(Date.now() - 1000), prorrogaInformacionUsada: extension } })
}
async function cleanup() {
  const negocios = await db.negocio.findMany({ where: { slug: { startsWith: prefix } }, select: { id: true } }); const ids = negocios.map(x => x.id)
  const clients = await db.cliente.findMany({ where: { email: { startsWith: prefix } }, select: { id: true } }); const clientIds = clients.map(x => x.id)
  const admins = await db.superAdmin.findMany({ where: { email: { startsWith: prefix } }, select: { id: true } }); const adminIds = admins.map(x => x.id)
  const solicitudes = ids.length ? await db.solicitudRevisionResena.findMany({ where: { negocioId: { in: ids } }, select: { id: true } }) : []
  const notificationRequestFilter = solicitudes.length ? { OR: solicitudes.map((solicitud) => ({ datos: { contains: solicitud.id } })) } : undefined
  await db.sesion.deleteMany({ where: { userId: { in: [...ids, ...clientIds, ...adminIds] } } }); await db.auditLog.deleteMany({ where: { userId: { in: [...ids, ...adminIds] } } }); await db.notificacion.deleteMany({ where: { userId: { in: [...ids, ...clientIds, ...adminIds] } } })
  if (notificationRequestFilter) await db.notificacion.deleteMany({ where: notificationRequestFilter })
  if (ids.length) { await db.evidenciaSolicitudRevisionResena.deleteMany({ where: { solicitud: { negocioId: { in: ids } } } }); await db.solicitudRevisionResenaEvento.deleteMany({ where: { solicitud: { negocioId: { in: ids } } } }); await db.solicitudRevisionResena.deleteMany({ where: { negocioId: { in: ids } } }); await db.resena.deleteMany({ where: { negocioId: { in: ids } } }); await db.pedido.deleteMany({ where: { negocioId: { in: ids } } }); await db.negocio.deleteMany({ where: { id: { in: ids } } }) }
  await db.cliente.deleteMany({ where: { id: { in: clientIds } } }); await db.superAdmin.deleteMany({ where: { id: { in: adminIds } } })
}
beforeAll(async () => { expect(process.env.DATABASE_URL).toBe(process.env.DELIGO_TEST_DATABASE_URL); await cleanup(); const [c,a,b,s] = await Promise.all([db.cliente.create({ data: { nombre: `${prefix}cliente`, email: `${prefix}cliente@example.test`, telefono: "" } }), db.negocio.create({ data: { nombre: `${prefix}a`, slug: `${prefix}a`, usuario: `${prefix}a`, email: `${prefix}a@example.test`, password: "fixture", aprobado: true } }), db.negocio.create({ data: { nombre: `${prefix}b`, slug: `${prefix}b`, usuario: `${prefix}b`, email: `${prefix}b@example.test`, password: "fixture", aprobado: true } }), db.superAdmin.create({ data: { email: `${prefix}admin@example.test`, googleSub: `${prefix}sub`, activo: true } })]); cliente=c.id; negocioA=a.id; negocioB=b.id; admin=s.id; tokenA=await createSession(a.id,"negocio") })
afterAll(async () => { await cleanup(); expect(await Promise.all([db.negocio.count({where:{slug:{startsWith:prefix}}}),db.cliente.count({where:{email:{startsWith:prefix}}}),db.superAdmin.count({where:{email:{startsWith:prefix}}})])).toEqual([0,0,0]) })

describe("19-D - informacion adicional PostgreSQL", () => {
  test("ruta valida body, historial propio e IDOR", async () => { const own=await createReview(negocioA,3,"own",true); const foreign=await createReview(negocioB,2,"foreign"); const solicitud=await createRequest(own.id); const headers={"content-type":"application/json",cookie:`${SESSION_COOKIE_NAME}=${tokenA}`}; expect((await postInformation(new NextRequest(`http://localhost/api/negocio/solicitudes-revision-resenas/${solicitud.id}/informacion-adicional`,{method:"POST",headers,body:JSON.stringify({mensaje:""})}),{params:Promise.resolve({id:solicitud.id})})).status).toBe(400); expect((await getHistory(new NextRequest(`http://localhost/api/negocio/resenas/${foreign.id}/solicitudes-revision`,{headers}),{params:Promise.resolve({id:foreign.id})})).status).toBe(404); expect((await getHistory(new NextRequest(`http://localhost/api/negocio/resenas/${own.id}/solicitudes-revision`,{headers}),{params:Promise.resolve({id:own.id})})).status).toBe(200) })
  test("primera informacion usa una extension, conserva ocultamiento y crea evento/audit", async () => { const review=await createReview(negocioA,1,"first"); const solicitud=await createRequest(review.id); const before=Date.now(); const result=await addBusinessReviewModerationInformation({negocioId:negocioA,solicitudId:solicitud.id,mensaje:"  contexto adicional  "}); expect(result.solicitud.estado).toBe("EN_REVISION"); const [stored,event,audit,resena]=await Promise.all([db.solicitudRevisionResena.findUniqueOrThrow({where:{id:solicitud.id}}),db.solicitudRevisionResenaEvento.findFirstOrThrow({where:{solicitudId:solicitud.id,tipo:"INFORMACION_APORTADA"}}),db.auditLog.findFirstOrThrow({where:{recursoId:solicitud.id,accion:"resena.moderacion_informacion_aportada"}}),db.resena.findUniqueOrThrow({where:{id:review.id}})]); expect(stored).toMatchObject({estado:"EN_REVISION",activeKey:review.id,prorrogaInformacionUsada:true}); expect(Math.abs(stored.venceEn.getTime()-getReviewModerationExpiry(new Date(before)).getTime())).toBeLessThan(60_000); expect(event.mensaje).toBe("contexto adicional"); expect(audit).toBeTruthy(); expect(resena.estadoModeracion).toBe("OCULTA_EN_REVISION") })
  test("doble informacion y segundo ciclo usan CAS y no duplican extension", async () => { const review=await createReview(negocioA,2,"double"); const solicitud=await createRequest(review.id); const results=await Promise.allSettled([addBusinessReviewModerationInformation({negocioId:negocioA,solicitudId:solicitud.id,mensaje:"uno"}),addBusinessReviewModerationInformation({negocioId:negocioA,solicitudId:solicitud.id,mensaje:"dos"})]); expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1); expect(results.filter(x=>x.status==="rejected"&&isReviewModerationBusinessConflict(x.reason))).toHaveLength(1); const first=await db.solicitudRevisionResena.findUniqueOrThrow({where:{id:solicitud.id}}); const expiry=first.venceEn; await mutateReviewModerationRequest({solicitudId:solicitud.id,superadminId:admin,action:"PEDIR_INFORMACION",text:"mas"}); await addBusinessReviewModerationInformation({negocioId:negocioA,solicitudId:solicitud.id,mensaje:"segundo"}); const second=await db.solicitudRevisionResena.findUniqueOrThrow({where:{id:solicitud.id}}); expect(second.venceEn).toEqual(expiry); expect(await db.solicitudRevisionResenaEvento.count({where:{solicitudId:solicitud.id,tipo:"INFORMACION_APORTADA"}})).toBe(2) })
  test("informacion versus aprobar nunca deja evento despues de terminal y rollback protege inconsistencia", async () => { const review=await createReview(negocioA,4,"race"); const solicitud=await createRequest(review.id); const race=await Promise.allSettled([addBusinessReviewModerationInformation({negocioId:negocioA,solicitudId:solicitud.id,mensaje:"aporte"}),mutateReviewModerationRequest({solicitudId:solicitud.id,superadminId:admin,action:"APROBAR",text:"decision"})]); expect(race.some(x=>x.status==="fulfilled")).toBe(true); const events=await db.solicitudRevisionResenaEvento.findMany({where:{solicitudId:solicitud.id},orderBy:{createdAt:"asc"}}); const approved=events.findIndex(x=>x.tipo==="APROBADA"), info=events.findIndex(x=>x.tipo==="INFORMACION_APORTADA"); expect(approved===-1||info===-1||info<approved).toBe(true); const bad=await db.resena.create({data:{negocioId:negocioA,clienteId:cliente,clienteNombre:"x",pedidoId:(await db.pedido.create({data:{negocioId:negocioA,negocioSlug:`${prefix}a`,negocioNombre:`${prefix}a`,clienteId:cliente,clienteNombre:"x",total:1,totalProductos:1,estado:"entregado",metodoEntrega:"retiro",metodoPago:"efectivo"}})).id,puntuacion:4,comentario:"bad"}}); const badRequest=await db.solicitudRevisionResena.create({data:{resenaId:bad.id,negocioId:negocioA,motivo:"FALSA",explicacionOriginal:"bad",estado:"REQUIERE_INFORMACION",activeKey:bad.id,venceEn:new Date()}}); await expect(addBusinessReviewModerationInformation({negocioId:negocioA,solicitudId:badRequest.id,mensaje:"x"})).rejects.toBeInstanceOf(Error); expect(await db.solicitudRevisionResenaEvento.count({where:{solicitudId:badRequest.id}})).toBe(0) })
})
